# Form implementation generated from reading ui file 'c:\Users\laiwa\wanqin\project\QtProject\stellarforge\stellarforge\stellarforge.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StellarForge(object):
    def setupUi(self, StellarForge):
        StellarForge.setObjectName("StellarForge")
        StellarForge.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=StellarForge)
        self.centralwidget.setObjectName("centralwidget")
        StellarForge.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=StellarForge)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        StellarForge.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=StellarForge)
        self.statusbar.setObjectName("statusbar")
        StellarForge.setStatusBar(self.statusbar)

        self.retranslateUi(StellarForge)
        QtCore.QMetaObject.connectSlotsByName(StellarForge)

    def retranslateUi(self, StellarForge):
        _translate = QtCore.QCoreApplication.translate
        StellarForge.setWindowTitle(_translate("StellarForge", "StellarForge"))
