# Form implementation generated from reading ui file 'c:\Users\laiwa\wanqin\project\QtProject\starrycard\starrycard\starrycard.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StarryCard(object):
    def setupUi(self, StarryCard):
        StarryCard.setObjectName("StarryCard")
        StarryCard.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=StarryCard)
        self.centralwidget.setObjectName("centralwidget")
        StarryCard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=StarryCard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        StarryCard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=StarryCard)
        self.statusbar.setObjectName("statusbar")
        StarryCard.setStatusBar(self.statusbar)

        self.retranslateUi(StarryCard)
        QtCore.QMetaObject.connectSlotsByName(StarryCard)

    def retranslateUi(self, StarryCard):
        _translate = QtCore.QCoreApplication.translate
        StarryCard.setWindowTitle(_translate("StarryCard", "StarryCard"))
